/* Generated by tools/fonts/build-game-fonts.mjs */
window.App = window.App || {};
App.GAME_FONTS = [
 {
  "family": "San Andreas Subtitles",
  "game": "GTA San Andreas",
  "style": "Subtitles & HUD"
 },
 {
  "family": "San Andreas Pricedown",
  "game": "GTA San Andreas",
  "style": "Title logo font"
 },
 {
  "family": "San Andreas Gothic",
  "game": "GTA San Andreas",
  "style": "Mission titles"
 },
 {
  "family": "San Andreas Menu",
  "game": "GTA San Andreas",
  "style": "Menus"
 },
 {
  "family": "L.A. Noire Chandler",
  "game": "L.A. Noire",
  "style": "Chandler 42 — case files (typewriter)"
 },
 {
  "family": "L.A. Noire Notebook",
  "game": "L.A. Noire",
  "style": "CCFaceFront — handwritten notebook"
 },
 {
  "family": "L.A. Noire Subtitles",
  "game": "L.A. Noire",
  "style": "News Gothic Demi — subtitles"
 },
 {
  "family": "L.A. Noire Futura",
  "game": "L.A. Noire",
  "style": "Futura — tutorials"
 },
 {
  "family": "L.A. Noire Typewriter",
  "game": "L.A. Noire",
  "style": "American Typewriter — location titles"
 },
 {
  "family": "L.A. Noire Heroic",
  "game": "L.A. Noire",
  "style": "Heroic Condensed Bold — menus & titles"
 }
];
